export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";

export const AUTHLOADING_TRUE = "AUTHLOADING";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const GET_CONTACTS = "GET_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACTS";
export const UPDATE_CONTACT = "UPDATE_CONTACTS";
export const CONTACT_ERROR = "CONTACT_ERROR";
export const LOADING_CONTACTS_TRUE = "LOADING_CONTACTS_TRUE";

export const SET_EDIT_CONTACT = "SET_EDIT_CONTACT";
export const CLEAR_EDIT_CONTACT = "DELETE_EDIT_CONTACT";

export const SET_CONTACT_TO_DELETE = "SET_CONTACT_TO_DELETE";
export const CLEAR_CONTACT_TO_DELETE = "CLEAR_CONTACT_TO_DELETE";

export const DELETE_CONTACT = "DELETE_CONTACT";
