export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const AUTHLOADING_TRUE = "AUTHLOADING";
export const LOADUSER = "LOADUSER";

export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const GET_CONTACTS = "GET_CONTACTS";
export const CONTACT_ERROR = "CONTACT_ERROR";
export const LOADING_CONTACTS_TRUE = "LOADING_CONTACTS_TRUE";
